apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../k8s/apps/base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: go-grpc
      namespace: example-stack
    path: go-grpc-regional-pricing-patch.yaml
