apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-flux
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: monitoring
  sourceRef:
    kind: GitRepository
    name: example-stack
  path: ./k8s/infra/monitoring-flux
  prune: true
  wait: true
  timeout: 2m
